import assert from 'node:assert/strict';
import { cachedPdf, digest, stableJson, previewDelay, waitForPreview } from '../../src/utils/previewJobs.js';
import { savedPreviewOptions } from '../../src/utils/savedPreviewOptions.js';

let builds = 0;
const build = async () => { builds++; await new Promise(r => setTimeout(r, 10)); return new Uint8Array([1, 2]); };
const [a, b] = await Promise.all([cachedPdf('same', build), cachedPdf('same', build)]);
assert.equal(builds, 1);
assert.equal(a, b);
assert.equal(await cachedPdf('same', build), a);
assert.equal(builds, 1, 'reopening unchanged revision reuses bytes');
await cachedPdf('new-revision', build);
assert.equal(builds, 2);
await assert.rejects(cachedPdf('failure', async () => { throw Error('offline'); }), /offline/);
await cachedPdf('failure', build);
assert.equal(builds, 3, 'failure is evicted and Retry succeeds');
const c1 = new AbortController();
const c2 = new AbortController();
const p1 = cachedPdf('shared', build, c1.signal);
const p2 = cachedPdf('shared', build, c2.signal);
c1.abort();
await assert.rejects(p1, { name: 'AbortError' });
await p2;
assert.equal(builds, 4, 'one cancelled consumer does not cancel another');
const cancelled = new AbortController();
let observedAbort = false;
const outdated = cachedPdf('outdated', async signal => {
  await new Promise(resolve => signal.addEventListener('abort', () => { observedAbort = true; resolve(); }));
  return new Uint8Array([9]);
}, cancelled.signal);
await new Promise(r => setTimeout(r, 0));
cancelled.abort();
await assert.rejects(outdated, { name: 'AbortError' });
assert.equal(observedAbort, true);
await cachedPdf('outdated', build);
assert.equal(builds, 5, 'cancelled output cannot populate the cache');
await assert.rejects(waitForPreview(new Promise(() => {}), undefined, 5), /timed out/);
let updates = 0;
let controller;
const edits = Array.from({ length: 10 }, () => {
  controller?.abort();
  controller = new AbortController();
  return previewDelay(controller.signal, 5).then(() => updates++, () => {});
});
await Promise.all(edits);
assert.equal(updates, 1, 'rapid edits generate once');
assert.equal(stableJson({ b: 2, a: 1 }), stableJson({ a: 1, b: 2 }));
assert.notEqual(await digest(new Uint8Array([1])), await digest(new Uint8Array([2])));
assert.throws(() => savedPreviewOptions({ submissionId: 'old' }, 'new'), /Saved revision/);
const saved = savedPreviewOptions({ submissionId: 's', questions: [{ marksAwarded: 3 }], finalObtainedMarks: 3, maxTotal: 4 }, 's');
assert.equal(saved.finalObtainedMarks, 3);
assert.equal(saved.skipCompress, true);
console.log('Preview cache, deduplication, debounce, cancellation, timeout, retry and saved revision checks passed.');
