import ExcelJS from "exceljs";
import { isStudentSubmitted, getResultMaxTotal } from "./markingFormData";
import { computeGradePercent } from "./reportGradePercent";
import { resolveTableGrade } from "./submissionGrades";
import {
  applyTitleRow,
  applyMetaLabel,
  applyMetaValue,
  applyKpiCell,
  applyTableHeader,
  applyDataCell,
  applyFooter,
  initBrandedWorkbook,
  GREEN_BG,
  RED_BG,
} from "./brandedExcelTheme";

export function scaleGradeToTarget({ assignedGrade, maxPoints, percentOverride, targetMax }) {
  const target = Number(targetMax);
  if (!Number.isFinite(target) || target <= 0) return null;

  const grade = Number(assignedGrade);
  const max = Number(maxPoints);
  if (!Number.isFinite(grade) || !Number.isFinite(max) || max <= 0) return null;

  const percentRaw =
    percentOverride != null && percentOverride !== ""
      ? percentOverride
      : computeGradePercent(grade, max);
  const percent = Number(percentRaw);
  if (!Number.isFinite(percent)) return null;

  return Math.round((percent / 100) * target * 100) / 100;
}

export function formatScaledGrade(scaled) {
  if (scaled == null || !Number.isFinite(scaled)) return null;
  return scaled.toFixed(2);
}

export function buildGradeExportRow(
  student,
  {
    targetMax,
    assignmentMaxPoints,
    savedResults,
    percentOverrides,
    gradeOverrides,
    classroomSyncedGrades,
  }
) {
  const name = String(student?.name || "—").trim() || "—";

  if (!isStudentSubmitted(student?.state)) {
    return { name, gradeDisplay: "didn't submit" };
  }

  const assignedGrade = resolveTableGrade(
    student.submissionId,
    student,
    gradeOverrides,
    savedResults,
    classroomSyncedGrades
  );

  const savedRow = savedResults?.[student.submissionId];

  const maxPoints =
    Number(assignmentMaxPoints) > 0
      ? Number(assignmentMaxPoints)
      : getResultMaxTotal(savedRow?.result) || null;

  const scaled = scaleGradeToTarget({
    assignedGrade,
    maxPoints,
    percentOverride: percentOverrides?.[student.submissionId],
    targetMax,
  });

  return {
    name,
    gradeDisplay: scaled != null ? formatScaledGrade(scaled) : "—",
  };
}

export function buildGradesExcelRows(students, options) {
  return (students || [])
    .map((student) => buildGradeExportRow(student, options))
    .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: "base" }));
}

export function sanitizeExcelFilenameBase(title) {
  return String(title || "assignment")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "_") || "assignment";
}

function triggerBrowserDownload(buffer, filename) {
  const blob = new Blob([buffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export async function downloadGradesExcel({
  filename,
  rows,
  targetMax,
  assignmentTitle,
  classroomName,
}) {
  const workbook = new ExcelJS.Workbook();
  const sheet = initBrandedWorkbook(workbook, "Grades");

  sheet.columns = [{ width: 34 }, { width: 16 }];

  const graded = (rows || []).filter((r) => r.gradeDisplay !== "didn't submit").length;
  const missing = (rows || []).length - graded;

  sheet.mergeCells("A1:B1");
  applyTitleRow(sheet.getCell("A1"), "Sahahly — Grade Export");
  sheet.getRow(1).height = 34;

  applyMetaLabel(sheet.getCell("A2"), "Assignment");
  applyMetaValue(sheet.getCell("B2"), assignmentTitle || "Assignment");

  applyMetaLabel(sheet.getCell("A3"), "Classroom");
  applyMetaValue(sheet.getCell("B3"), classroomName || "—");

  applyMetaLabel(sheet.getCell("A4"), "Scale");
  applyMetaValue(sheet.getCell("B4"), `Out of ${targetMax}`);

  applyKpiCell(sheet.getCell("A5"), "Graded", graded, GREEN_BG);
  applyKpiCell(sheet.getCell("B5"), "Didn't submit", missing, RED_BG);
  sheet.getRow(5).height = 22;

  const headerRowNum = 7;
  applyTableHeader(sheet.getCell(headerRowNum, 1), "Name");
  applyTableHeader(sheet.getCell(headerRowNum, 2), `Grade (/${targetMax})`);
  sheet.getRow(headerRowNum).height = 22;

  (rows || []).forEach((row, idx) => {
    const rowNum = headerRowNum + 1 + idx;
    const zebra = idx % 2 === 1;
    const isMissing = row.gradeDisplay === "didn't submit";
    applyDataCell(sheet.getCell(rowNum, 1), row.name, { zebra });
    applyDataCell(sheet.getCell(rowNum, 2), row.gradeDisplay, {
      status: isMissing ? "didn't submit" : undefined,
      zebra,
    });
    sheet.getRow(rowNum).height = 20;
  });

  const footerRow = headerRowNum + (rows?.length || 0) + 2;
  sheet.mergeCells(`A${footerRow}:B${footerRow}`);
  applyFooter(
    sheet.getCell(`A${footerRow}`),
    `Generated by Sahahly · ${new Date().toLocaleString("en-GB")}`
  );

  const buffer = await workbook.xlsx.writeBuffer();
  triggerBrowserDownload(buffer, filename);
}

export async function exportAssignmentGradesExcel({
  students,
  targetMax,
  assignmentMaxPoints,
  savedResults,
  percentOverrides,
  gradeOverrides,
  classroomSyncedGrades,
  filename,
  assignmentTitle,
  classroomName,
}) {
  const rows = buildGradesExcelRows(students, {
    targetMax,
    assignmentMaxPoints,
    savedResults,
    percentOverrides,
    gradeOverrides,
    classroomSyncedGrades,
  });
  await downloadGradesExcel({
    filename,
    rows,
    targetMax,
    assignmentTitle,
    classroomName,
  });
}
